### PR TITLE
KAF-210 Pulsar Sink - part1 - create "common" module

### PR DESCRIPTION
**Pull request by eolivelli**
This patch introduces a new "common" module that contains most of the logic of the Connector.
This Common Module will be shared with the new PulsarSink, leveraging all of the Cassandra related code.

Changes:
-  Create a new "common" module
- Move all code that is not related to Kafka to the Common Module
- Create interfaces that model KafkaConnect/Pulsar IO data model: SInkRecord, Struct and Schema are the most important

Notes:
- We are only adding the new module in this patch, trying to move as less stuff as possible, in order to ease review
- We are keeping the kafka-clients jar dependency in "common" because we want to be 100% compatible with the Configuration framework. Rewriting a new configuration framework could lead to wrong default values and wrong conversions (in the Pulsar Sink we are going to use the maven shade plugin and keep only what is really useful, that is AbstractConfig and ConfigDef classes)
- In Kafka Sink are a wrapping all of the Kafka classes with implementations of the new interfaces, the new interfaces are modelled after Kafka classes, so the mapping 1-1
- The only complication is about the handling of Structs, that we are wrapping with a new KafkaStruct class, this in turn required a little change in the Codec

Tests:
- We are not adding tests, but all current tests are passing, practically without changes
- Many tests in the Kafka Sink have been copied into the Common module, this way we are both testing the "Common" classes with custom mock implementations AND also with the Kafka implementation (you will see some duplicate test classes, in "common" and in "sink", but the contents are a little different because we want to use the same Kafka Connect model in the tests

### CODE REVIEW

**Review by tomekl007 — COMMENTED** [review]
It seems that this PR has a lot more code than the initial PR. What are the differences here? (3k LOC vs 11k)

**Comment by eolivelli** [comment]
>  than the initial PR

what do you mean ? do you mean #122  or #124 ?

**Comment by eolivelli** [comment]
it is mostly about:
- changing package name
- introduce Abstractions (AbstractSchema....)
- adding new tests

**Comment by eolivelli** [comment]
I have pushed the wrong branch

**Review by tomekl007 — APPROVED** [review]

**Pull request merged**
